[
  # Existing warning baseline. Remove entries as the corresponding type specs are tightened.
  {"lib/aerospike.ex", "Function scan_stream!/2 has no local return."},
  {"lib/aerospike.ex", "Function scan_stream!/3 has no local return."},
  {"lib/aerospike.ex",
   "The pattern can never match the type \n  {:error,\n   %Aerospike.Error{\n     :__exception__ => true,\n     :code => atom(),\n     :in_doubt => boolean(),\n     :message => binary(),\n     :node => nil | binary()\n   }}\n."},
  {"lib/aerospike.ex", "Function stream!/2 has no local return."},
  {"lib/aerospike.ex", "Function stream!/3 has no local return."},
  {"lib/aerospike.ex", "Function query_stream!/2 has no local return."},
  {"lib/aerospike.ex", "Function query_stream!/3 has no local return."},
  {"lib/aerospike.ex", "Function query_all!/2 has no local return."},
  {"lib/aerospike.ex", "Function query_all!/3 has no local return."},
  {"lib/aerospike.ex", "Function scan_all!/2 has no local return."},
  {"lib/aerospike.ex", "Function scan_all!/3 has no local return."},
  {"lib/aerospike.ex", "Function scan_page!/2 has no local return."},
  {"lib/aerospike.ex", "Function scan_page!/3 has no local return."},
  {"lib/aerospike.ex", "Function all!/2 has no local return."},
  {"lib/aerospike.ex", "Function all!/3 has no local return."},
  {"lib/aerospike.ex", "Function query_count!/2 has no local return."},
  {"lib/aerospike.ex", "Function query_count!/3 has no local return."},
  {"lib/aerospike.ex", "Function query_page!/2 has no local return."},
  {"lib/aerospike.ex", "Function query_page!/3 has no local return."},
  {"lib/aerospike.ex", "Function query_aggregate_result!/5 has no local return."},
  {"lib/aerospike.ex", "Function query_aggregate_result!/6 has no local return."},
  {"lib/aerospike.ex", "Function scan_count!/2 has no local return."},
  {"lib/aerospike.ex", "Function scan_count!/3 has no local return."},
  {"lib/aerospike.ex", "Function count!/2 has no local return."},
  {"lib/aerospike.ex", "Function count!/3 has no local return."},
  {"lib/aerospike.ex", "Function put_payload!/3 has no local return."},
  {"lib/aerospike.ex", "Function put_payload!/4 has no local return."},
  {"lib/aerospike/command/admin.ex",
   "The pattern can never match the type \n  {:error,\n   :incomplete_header\n   | :truncated_admin_frame\n   | :unexpected_admin_message_type\n   | :unexpected_admin_proto_version}\n."},
  {"lib/aerospike/command/apply_udf.ex",
   "Function maybe_track_txn_in_doubt/4 will never be called."},
  {"lib/aerospike/command/batch.ex", "The function call run will not succeed."},
  {"lib/aerospike/command/operate.ex",
   "Function maybe_track_txn_in_doubt/5 will never be called."},
  {"lib/aerospike/command/put_payload.ex", "Function public_result/1 will never be called."},
  {"lib/aerospike/command/scan_ops.ex",
   "The pattern can never match the type \n  {:error,\n   %Aerospike.Error{\n     :__exception__ => true,\n     :code => atom(),\n     :in_doubt => boolean(),\n     :message => binary(),\n     :node => nil | binary()\n   }}\n."},
  {"lib/aerospike/command/scan_ops/page_runner.ex",
   "The pattern can never match the type \n  {:error,\n   %Aerospike.Error{\n     :__exception__ => true,\n     :code => atom(),\n     :in_doubt => boolean(),\n     :message => binary(),\n     :node => nil | binary()\n   }}\n."},
  {"lib/aerospike/command/scan_ops/page_runner.ex",
   "Function collect_all/5 will never be called."},
  {"lib/aerospike/command/scan_ops/page_runner.ex",
   "Function collect_all_node/6 will never be called."},
  {"lib/aerospike/command/scan_ops/page_runner.ex",
   "Function run_tracker_page/7 has no local return."},
  {"lib/aerospike/command/scan_ops/page_runner.ex",
   "Function run_tracker_page/8 has no local return."},
  {"lib/aerospike/command/scan_ops/page_runner.ex",
   "Function prepare_iteration/4 will never be called."},
  {"lib/aerospike/command/scan_ops/page_runner.ex",
   "Function continue_tracker_page/7 will never be called."},
  {"lib/aerospike/command/scan_ops/page_runner.ex",
   "Function run_page_jobs/5 has no local return."},
  {"lib/aerospike/command/scan_ops/page_runner.ex",
   "The function call run_node_requests will not succeed."},
  {"lib/aerospike/command/scan_ops/page_runner.ex",
   "Function maybe_sleep_between_iterations/1 will never be called."},
  {"lib/aerospike/command/scan_ops/page_runner.ex",
   "Function cursor_from_filter/1 will never be called."},
  {"lib/aerospike/command/scan_ops/page_runner.ex",
   "Function attach_cursor/2 will never be called."},
  {"lib/aerospike/command/scan_ops/stream_runner.ex",
   "The function call run_node_requests will not succeed."},
  {"lib/aerospike/command/unary_command.ex", "Invalid type specification for function run."},
  {"lib/aerospike/command/unary_support.ex", "Function run_command/5 has no local return."},
  {"lib/aerospike/command/unary_support.ex", "The function call run will not succeed."},
  {"lib/aerospike/query/aggregate_reducer.ex", "Function run_lua/3 has no local return."},
  {"lib/aerospike/query/aggregate_reducer.ex", "The function call run will not succeed."},
  {"lib/aerospike/query/aggregate_reducer.ex",
   "Function decode_final_results/2 will never be called."},
  {"lib/aerospike/query/aggregate_reducer.ex",
   "Function decode_lua_value/2 will never be called."},
  {"lib/aerospike/query/aggregate_reducer.ex", "Function list_value/1 will never be called."},
  {"lib/aerospike/query/aggregate_reducer.ex", "Function one_result/1 will never be called."},
  {"lib/aerospike/runtime/txn_monitor.ex",
   "The pattern can never match the type \n  {:error,\n   %Aerospike.Error{\n     :__exception__ => true,\n     :code => atom(),\n     :in_doubt => boolean(),\n     :message => binary(),\n     :node => nil | binary()\n   }}\n."},
  {"lib/aerospike/runtime/txn_roll.ex",
   "The pattern can never match the type \n  {:error,\n   %Aerospike.Error{\n     :__exception__ => true,\n     :code => atom(),\n     :in_doubt => boolean(),\n     :message => binary(),\n     :node => nil | binary()\n   }}\n."},
  {"test/support/stream_proof.ex",
   "Function seed_records_on_master_partitions!/6 has no local return."},
  {"test/support/stream_proof.ex",
   "Type mismatch in call without opaque term in master_partitions!."},
  {"test/support/stream_proof.ex",
   "Function records_on_master_partitions!/5 will never be called."},
  {"test/support/stream_proof.ex", "Function maybe_keep_master_key/6 will never be called."},
  {"test/support/stream_proof.ex",
   "Function maybe_halt_master_key_search/5 will never be called."},
  {"test/support/stream_proof.ex", "Function write_seed_record!/4 will never be called."},
  {"test/support/stream_proof.ex", "Function scan_request/4 has no local return."},
  {"test/support/stream_proof.ex", "Function master_partitions!/2 has no local return."},
  {"test/support/stream_proof.ex", "Type mismatch in call without opaque term in info."}
]
