service {
	cluster-name security-tls-test
	proto-fd-max 15000
}

logging {
	console {
		context any info
	}
}

network {
	service {
		address any
		port 3000
		tls-address any
		tls-port 4433
		tls-name localhost
		tls-authenticate-client false
	}

	heartbeat {
		mode mesh
		address local
		port 3002
		interval 150
		timeout 10
	}

	fabric {
		address local
		port 3001
	}

	tls localhost {
		cert-file /opt/aerospike/tls/server.crt
		key-file /opt/aerospike/tls/server.key
		ca-file /opt/aerospike/tls/ca.crt
	}
}

security {
	enable-quotas true
}

namespace test {
	replication-factor 1
	default-ttl 0

	storage-engine memory {
		data-size 512M
	}
}
